version: "3.8"

services:
  nowen-note:
    build: .
    container_name: nowen-note
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      - nowen-note-data:/app/data
    environment:
      - NODE_ENV=production
      - DB_PATH=/app/data/nowen-note.db
      - PORT=3001

volumes:
  nowen-note-data:
    driver: local
